cool lights emojis
TrafficFlowOptimizer/frontend pull request #20
Opened 2023-12-06 22:48 UTC by Loloxon

2023-12-07 09:34 UTC, Y3drk commented on src/components/flow/ResultsAsDescription.tsx
>  	return (
Usuń później

2023-12-07 09:36 UTC, Y3drk commented on src/components/flow/ResultsAsSimulation.tsx
> +		let result = [
po co tutaj let? Jak nie zmieniasz tego nigdzie później (w sensie nie podmieniasz całego obiektu) to wal consta bez strachu

2023-12-07 09:37 UTC, Y3drk commented on src/components/flow/ResultsAsSimulation.tsx
> +			const shift = 1 + i * 2 - Math.ceil((usedLights.length * 1.99) / 2);
W momencie, w którym to nie bedzie już tmp to weź wynieś te numerki do jakichś constów wyżej, bo przybywa magic numbers i ja np. nie mam pojecia co one oznaczaja

2023-12-07 09:40 UTC, Y3drk commented on src/components/flow/ResultsAsSimulation.tsx
> +							10 * shift +
to "*10" może by przenieść już do wyliczania shifta?

2023-12-07 09:46 UTC, Y3drk commented on src/components/flow/ResultsAsSimulation.tsx
> +				></EEIPointMarker>,
Może by tak odwrócić kolejność, bo tak to zawsze jak jest jedno światło to przechodzisz przez pętlę a potem podmieniasz tablicę na to, a tak to  można by if else'm ograć, że dopiero jak jest wiecej niz 1 element to odpala się for

2023-12-07 09:50 UTC, Y3drk commented on src/styles/drawing-tool-styles/GeneralStyles.ts
> +`;
Co ta 2 tu robi? Nie czaje kompletnie ocb... Tym bardziej, ze to jest takie samo jak pierwsza wersja + tego nigdzie nie używasz???

2023-12-07 09:53 UTC, Y3drk requested changes
Jest spoko, ale parę micro-poprawek można zrobić

2023-12-07 21:15 UTC, Loloxon commented on src/styles/drawing-tool-styles/GeneralStyles.ts
> +`;
a nie wiem skąd to się wzięło wgl xdd

2023-12-08 10:24 UTC, Y3drk approved these changes
Jest ok jak na ciebie :)

2023-12-08 16:31 UTC, merged